"use client";

import "./globals.css";

import { RecoilRoot } from "recoil";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="">
      <RecoilRoot>
        <body>{children}</body>
      </RecoilRoot>
    </html>
  );
}
